<?php include('header.php'); ?>
        <!-- Sidebar Start -->
<?php 
$type = $_SESSION['AccountType'];
switch ($type) {
    case 'Admin':
        include('includes_admin/navbar.php'); 
        break;
    case 'Player':
        include('includes_players/navbar.php'); 
        break;
    case 'Club':
        include('includes_club/navbar.php'); 
        break;
    
    default:
        // code...
        break;
}
?>
<!-- Sidebar End -->
<div class="container-fluid pt-4 px-4">
    <div class="row g-4">
        <h1>Legal Document</h1>
        <pre>
Cricket Player Performance Evaluation and Prediction System - Terms of Use
1. Introduction

This document outlines the Terms of Use ("Terms") for the Cricket Player Performance Evaluation and Prediction System (the "System"). The System is a web-based platform that allows administrators ("Admins"), players ("Players"), and clubs ("Clubs") to evaluate past performance and predict future potential using statistical analysis and machine learning.

2. Acceptance of Terms

By accessing, using, or registering for the System, you ("You" or "Your") agree to be bound by these Terms. If You do not agree to all the Terms, You may not access or use the System.

3. Roles and Responsibilities

3.1 Admins

Admins are responsible for managing the System, including user accounts, data management, and system configuration.
Admins will have access to all user data and performance metrics.
Admins are responsible for maintaining the confidentiality and security of user data.
Admins may remove or suspend user accounts for violating these Terms.
3.2 Players

Players can register for an account to access their performance evaluations and predictions.
Players can view their past performance statistics and predicted future performance.
Players are responsible for providing accurate and up-to-date information during registration.
Players are responsible for maintaining the confidentiality of their login credentials.
3.3 Clubs

Clubs can register for an account to access performance evaluations and predictions of their players.
Clubs are responsible for designating authorized representatives to access the System on their behalf.
Clubs are responsible for ensuring their representatives comply with these Terms.
Clubs acknowledge that player performance data belongs to the individual player and may be accessed by the player at any time.
4. Data Privacy

The System collects and stores data related to player performance.
All user data will be stored securely in accordance with applicable data privacy laws.
Players have the right to access, modify, or delete their personal data at any time through the System.
We will not share user data with any third party without prior consent, except as required by law.
5. Intellectual Property

The System and all related intellectual property rights belong to [Your Company Name] or its licensors.
You are granted a non-exclusive, non-transferable license to access and use the System in accordance with these Terms.
You may not reverse engineer, decompile, or disassemble the System.
6. Disclaimer of Warranties

The System is provided "as is" and without warranties of any kind, express or implied.
We disclaim all warranties, including warranties of merchantability, fitness for a particular purpose, and non-infringement.
We do not guarantee the accuracy, completeness, or reliability of any performance evaluations or predictions generated by the System.
7. Limitation of Liability

We will not be liable for any damages arising out of or related to Your use of the System, including but not limited to direct, indirect, incidental, consequential, or punitive damages.
8. Termination

We may terminate Your access to the System at any time for any reason.
You may terminate Your access to the System at any time by deleting Your account.
9. Governing Law and Dispute Resolution

These Terms will be governed by and construed in accordance with the laws of [Your Jurisdiction].
Any dispute arising out of or related to these Terms will be subject to the exclusive jurisdiction of the courts located in [Your Jurisdiction].
10. Entire Agreement

These Terms constitute the entire agreement between You and us regarding Your use of the System.
11. Updates to Terms

We may update these Terms at any time by posting the revised Terms on the System.
Your continued use of the System after the revised Terms are posted constitutes Your acceptance of the revised Terms.
12. Contact Us

If You have any questions about these Terms, please contact us at [Your Email Address].

Please note: This is a sample legal document and may not be suitable for all situations. You should consult with an attorney to ensure that the Terms are appropriate for your specific needs.

        </pre>
    </div>
</div>
<?php include('footer.php'); ?>